meta_product_name: "Shifted"
meta_title: "Shifted - Finally loving work planning"
meta_description: "Shifted is an app for nurses, that helps with planning and organizing their shifts."
meta_image: "doctor_og.png"
